### ISSUE TITLE
how to use it to login or do you have the db

### ISSUE THREAD

**Issue by zyw-yw** [akshatshah21/SCMO#1]
i can use it to to the next page after login

**Comment by akshatshah21** [comment]
Hi, I'm assuming you are asking about how to set up the database for this project. There is no shared, maintained database currently for this project, so you will have to set up your own local database. Please refer to [SETUP.md](https://github.com/akshatshah21/SCMO/blob/main/SETUP.md) and set up the Neo4j and PostgreSQL databases as outlined. 

As for the login, you can create a user directly using the Register screen. Of course, do this only after setting up the databases.

**Comment by akshatshah21** [comment]
Closing this issue.
